---
services:
  backend:
    image: menagerist-backend
    container_name: menagerist-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
